apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-eks-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: AWS_ECR_URI
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
