apiVersion: v1
kind: Service
metadata:
  name: cb-test-api
  namespace: prd-api
spec:
  type: LoadBalancer
  selector: 
    app: cb-test-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
